[build]
  command = "npm run build"
  publish = "build/"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/movie/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/plays/*"
  to = "/index.html"
  status = 200
